kind: Pod
apiVersion: v1
metadata:
  name: busybox
  namespace: demo
spec:
  serviceAccountName: app-sa
  containers:
  - image: k8s.gcr.io/e2e-test-images/busybox:1.29
    name: busybox
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sleep"
    - "10000"
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 100Mi
    volumeMounts:
    - name: vault-database
      mountPath: "/mnt/secrets-store"
      readOnly: true
    # Uncomment after syncing the Vault data with a Kubernetes Secret  
    # env:
    # - name: API_TOKEN
    #   valueFrom:
    #     secretKeyRef:
    #       name: kvsecret-1
    #       key: token
  volumes:
    - name: vault-database
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-database"