apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
  namespace: demo
spec:
  provider: vault                             
  parameters:
    vaultAddress: "http://vault.demo:8200"
    roleName: "database"
    objects: |
      - objectName: "token"
        secretPath: "secret/data/token"
        secretKey: "token"
  # Uncomment to sync a Kubernetes Secret       
  # secretObjects:
  # - secretName: kvsecret-1
  #   type: Opaque
  #   data: 
  #   - objectName: token
  #     key: token